### PR TITLE
Prepare analyzer 3.2.0 release.

### PR DESCRIPTION
**Pull request by aomarks**
- [ ] polymer-analyzer@3.2.0

### CODE REVIEW

**Comment by usergenic** [comment]
(approved except for builds breaking...)

**Comment by usergenic** [comment]
Assume this is because `npm run nuke` updated TypeScript to 3.2.1 from 3.1.6?

**Comment by aomarks** [comment]
> Fix typings or pin TS back to 3.1.6?

I can fix the typings.

**Comment by aomarks** [comment]
> I can fix the typings.

I think I fixed the typings. Not very proud of the fixes, they seem worse in every case.

**Comment by usergenic** [comment]
I don't think the changes are all that bad.

The ones in the tests are to be expected because of the way `.args` is going to be ambiguous.  I do agree that adding `as any` into the code at places feels bad, but I think that's often more a matter of some limitations in the typings we're getting for libraries like with sinon etc.

Anyways lgtm

**Pull request merged**
