### PR TITLE
[build] Update babel to 7.0.0, add isNativeFunction helper

### LINKED ISSUE #398: Babel v7 (rc) prevents the custom elements polyfill from finding element definitions.
#216 pins @babel/plugin-transform-classes to a particular version to avoid a problem with the way that they transformed classes extending built-in constructors. babel/babel#7533 fixes this problem. Once it's in a tagged release, we should revert #216.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #398 

Confirmed working with web-padawan/polymer3-webpack-starter@4775c2d

---
This change is [Reviewable](https://reviewable.io/reviews/polymer/tools/670)

### CODE REVIEW

**Comment by TimvdLippe** [comment]
(CI didnt like it though :cry: )

**Comment by web-padawan** [comment]
Looks like the failing test has to be updated or removed, will look into it tomorrow.

**Comment by hastebrot** [comment]
So, `yarn install` gave me warnings in the past when it installed `polymer-build`.

~~~
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "polymer-cli > polymer-build > @babel/plugin-transform-classes@7.0.0-beta.35" has incorrect peer dependency "@babel/core@7.0.0-beta.35".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 96.92s.
~~~

Looks like an issue on `@babel` side. I haven't tested this feature branch, yet.

**Comment by web-padawan** [comment]
@aomarks I have updated the goldens but there seem to be still failures likely not related to this PR.
Feel free to modify this PR or merge into separate branch in case you want to confirm everything is ok.

**Comment by web-padawan** [comment]
So, babel 7.0.0 is released and this PR needs another update.
Should I rebase, nuke and update goldens once #664 is merged? @usergenic @aomarks WDYT?

**Comment by usergenic** [comment]
We don't have to wait for #664 -- this PR is awesome, btw THANK you for it.  Lets update to babel 7 nuke, update goldens and I'll merge as soon as verify its not breaking anything.

**Comment by usergenic** [comment]
@web-padawan thanks again for this contribution.

**Comment by web-padawan** [comment]
@usergenic executed `npm run nuke && npm run update-goldens`

Wondering if my local setup is incorrect. I have seen `polyserve` saying it updated goldens too, but only 3 fixtures for CLI have been marked in git as changed after the script terminated.

**Comment by web-padawan** [comment]
@usergenic executed `npm run nuke && npm run update-goldens`

There is one failure in Travis unrelated to this PR:
```
@polymer/esm-amd-loader: chrome 62                Tests failed: {"value":{"stacktrace":"org.openqa.selenium.SessionNotCreatedException: session not created exception: Chrome version must be >= 66.0.3359.0\n  (Driver info: chromedriver=2.40.565383 
```

Other that that, I believe this should be ready to merge. 
Note this PR only targets `polymer-build` where exact version matters, I haven't tried updating other packages (some of those still use Babel 6).

**Comment by usergenic** [comment]
Thanks, @web-padawan looking at this now.

**Comment by web-padawan** [comment]
@usergenic it will fail for external contributions because of this line: https://github.com/Polymer/tools/blob/bf6b44904e1b6034eb70dd63e4cffa4a9e03b87d/packages/esm-amd-loader/test/run-wct.sh#L6

Chrome 62 is the latest version installed in Travis by default when using config:
```yaml
apt:
  sources:
    - google-chrome
```
I'm just not sure where to tweak `wct-local` config to get those tests passing.

**Comment by web-padawan** [comment]
Note it is not supposed to be started at all, actually: https://github.com/Polymer/tools/blob/bf6b44904e1b6034eb70dd63e4cffa4a9e03b87d/.travis.yml#L67

**Comment by usergenic** [comment]
So, the esm-amd-loaders tests don't honor the SKIP_LOCAL_BROWSERS=true (that's only for WCT's own integration tests.)

However the bit about the `npx wct --plugin local` failing for external contributions, that's worth checking out.  Perhaps the way to solve this is to merge the PR into a branch and run the tests and then I can merge to master.  Updating PR one moment...

**Pull request merged**
