### PR TITLE
Web padawan bump babel

### PR DESCRIPTION
**Pull request by usergenic**
Use this PR to invoke integration tests on sauce for @web-padawan's merged PR https://github.com/Polymer/tools/pull/670

### CODE REVIEW

**Comment by web-padawan** [comment]
Thanks for merging! For history: I confirm that I have signed the CLA.

**Comment by usergenic** [comment]
I need to investigate this further, looking at Sauce labs screenshot it looks like maybe there's a legit server error in the test that's failing for IE11...
screen shot 2018-08-30 at 2 56 22 pm

**Comment by usergenic** [comment]
Hmm, when I run the tests on my local box and connect to sauce, IE11 is fine.  So not sure why travis calling out to sauce is a problem...  I'm leaning towards merging this.  Was just concerned that IE11 requesting page somehow triggered wct/polyserve to 500 because of a middleware transforming response to adapt to IE11's browser capabilities spec.

**Comment by usergenic** [comment]
```
λ nvm install 10
Downloading https://nodejs.org/dist/v10.9.0/node-v10.9.0-darwin-x64.tar.gz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Downloading and installing node v10.9.0...
Now using node v10.9.0 (npm v6.2.0)
~/s/g/P/tools~web-padawan-bump-babel λ npx lerna run test:integration --scope @polymer/esm-amd-loader --stream
lerna notice cli v3.2.1
lerna info versioning independent
lerna info filter [ '@polymer/esm-amd-loader' ]
@polymer/esm-amd-loader: > @polymer/esm-amd-loader@1.0.2 test:integration /Users/brendanb/src/github.com/Polymer/tools~web-padawan-bump-babel/packages/esm-amd-loader
@polymer/esm-amd-loader: > cd test/ && npm run test:wct
@polymer/esm-amd-loader: > @polymer/esm-amd-loader-test@0.1.0 test:wct /Users/brendanb/src/github.com/Polymer/tools~web-padawan-bump-babel/packages/esm-amd-loader/test
@polymer/esm-amd-loader: > bash run-wct.sh
@polymer/esm-amd-loader: [BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
@polymer/esm-amd-loader: [BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
@polymer/esm-amd-loader: Windows 8.1 IE 11        Beginning tests via http://localhost:8081/components/@polymer/esm-amd-loader-test/generated-index.html?cli_browser_id=0
@polymer/esm-amd-loader: OS X 10.13 safari latest Beginning tests via http://localhost:8081/components/@polymer/esm-amd-loader-test/generated-index.html?cli_browser_id=2
@polymer/esm-amd-loader: [BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
@polymer/esm-amd-loader: Windows 10 microsoftedge latest Beginning tests via http://localhost:8081/components/@polymer/esm-amd-loader-test/generated-index.html?cli_browser_id=1
@polymer/esm-amd-loader: Windows 8.1 IE 11        Tests passed
@polymer/esm-amd-loader: Windows 10 microsoftedge latest Tests passed
@polymer/esm-amd-loader: OS X 10.13 safari latest Tests passed
@polymer/esm-amd-loader: Test run ended with great success
@polymer/esm-amd-loader: Windows 8.1 IE 11 (50/0/0)            
@polymer/esm-amd-loader: Windows 10 microsoftedge latest (50/0/0)
@polymer/esm-amd-loader: OS X 10.13 safari latest (50/0/0)     
lerna success run Ran npm script 'test:integration' in 1 package:
lerna success - @polymer/esm-amd-loader
```

I'm going to merge this.

**Comment by web-padawan** [comment]
@usergenic any chance to get this released this week? thanks in advance!

**Pull request merged**
