### PR TITLE
Make WCT integration tests reliable again for the first time

### PR DESCRIPTION
**Pull request by usergenic**
This is a work in progress.  The PR is here right now as a convenience to get Travis to execute.  Not ready for review yet.

### CODE REVIEW

**Comment by bicknellr** [comment]
BTW, analyzer tests are failing because of #188.

**Comment by usergenic** [comment]
@bicknellr Yes I broke them.  I just unilaterally fixed them again in #239.

**Comment by bicknellr** [comment]
Ok, cool. Fingers crossed for this PR!

**Comment by usergenic** [comment]
And then again in f8daf698d306140448c1a63439b80a2b2d14f672

I am not touching typings again for a while.

**Comment by usergenic** [comment]
This PR is superseded by actual working code already in master.

**Pull request closed without merging**
