### PR TITLE
fix(web-component-tester): add location.search to subsuite title

### LINKED ISSUE #3351: [wct] Failures with shady are indistinguishable form failures without in the logs
## Current Behaviour

When a running a suite of test with WCT, with both shady and non-shady configuration set in loadSuites (like in: https://github.com/PolymerElements/iron-behaviors/blob/master/test/index.html#L20). If one of them fails, you will not be able to say from the reports which one has failed, as subsuites are named with the html name without que search part of `location`.

## Expected behaviour

The reports should include the search parameters used when invoking the HTML containing the subsuite.

### PR DESCRIPTION
**Pull request by alfonso-presa**
... to distinguish failures when reusing the same HTML suite for shady or non-shady DOM testing. Like in: https://github.com/PolymerElements/iron-behaviors/blob/master/test/index.html#L20

fixes: #3351

### CODE REVIEW

**Review by TimvdLippe — APPROVED** [review]
This is great! Let's still get a review from the tools team, but I am :+1:

**Comment by alfonso-presa** [comment]
@TimvdLippe Thanks for the quick feedback. Looks like I missed some failing tests, sorry.... I didn't get those failures locally. I'm going to review and update ASAP.

**Comment by alfonso-presa** [comment]
Seems like travis is complaining about the [`esm-amd-loader` build](https://travis-ci.org/Polymer/tools/jobs/490540187#L691) . I see this failing in other PR's so I'm assuming this is not to be blamed on this PR. If it is, please let me know and I'll try my best to solve it.

Also I would appreciate any comments if there's something to be improved in the PR to make it ready to be merged.

**Comment by alfonso-presa** [comment]
Any feedback on this? Anything I can do to speed it's merge?

**Comment by alfonso-presa** [comment]
Sorry to be a PITA.... any news here? What are the expectations of getting this merged? This is kind of breaking out tool chain on top of WCT, so I would be thankful if someone, based in experience, and of course without any compromise, can provide any order of magnitude estimate for the merge (days.... weeks..... months.... years...) to allow us to handle our internal expectations appropriately. Thanks!

**Comment by alfonso-presa** [comment]
Any news please...

**Pull request closed without merging**
