### PR TITLE
Use `npm ci` on travis and appveyor

### PR DESCRIPTION
**Pull request by rictic**
More consistent, and saves about a minute (15%) for each unit test run on travis.

### CODE REVIEW

**Comment by rictic** [comment]
More consistent, and 15% faster total time on unit tests.

**Comment by rictic** [comment]
Before:
screen shot 2018-05-01 at 2 41 31 pm


After
screen shot 2018-05-01 at 2 40 55 pm

**Comment by TimvdLippe** [comment]
This huge commit though: https://github.com/Polymer/tools/pull/278/commits/56945724ded1b98f5886a133fff2e5a5b6ee6a26 😂

**Comment by rictic** [comment]
Package lock files man. ¯\\\_(ツ)\_/¯

**Pull request merged**
