### PR TITLE
Friendlier nuke script

### PR DESCRIPTION
**Pull request by usergenic**
The old nuke script runs `npm install` before the bootstrap which is problematic when you have a package that isn't yet published, for example.  Also, this is not what lerna bootstrap package-locks are supposed to look like, so I wanted to avoid it doing this.  However, the `npm install` step was added by @TimvdLippe previously because the `npm audit` command would fail when hitting a package without a package-lock, which occurs in bootstrapped packages that have zero dependencies, in our case, that's `cleankill`.  So to solve the missing package-lock problem I just run `npm install --package-lock-only` on any package that doesn't have one, after the bootstrap.

This solved a recurring pain-point of being able to nuke/update the `wct-mocha-extraction` branch I'm working on which has unpublished packages.

Here's an example run of it adding missing package-lock.json to cleankill:

```
λ npm run nuke

> polymer-tools@ nuke /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script
> rm -rf package-lock.json node_modules && npm install && lerna exec "rm -f package-lock.json npm-shrinkwrap.json" && lerna clean --yes && lerna bootstrap && lerna exec --stream -- "bash -c \"test ! -f package-lock.json && npm install --package-lock-only || true\""

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN sinon-chai@3.2.0 requires a peer of sinon@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.

added 652 packages from 818 contributors and audited 35789 packages in 14.742s
found 0 vulnerabilities

lerna notice cli v3.2.1
lerna info versioning independent
lerna success exec Executed command in 21 packages: "rm -f package-lock.json npm-shrinkwrap.json"
lerna notice cli v3.2.1
lerna info versioning independent
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/analyzer/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/browser-capabilities/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/build/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/bundler/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/cleankill/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/cli/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/common/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/dom5/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/editor-service/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/esm-amd-loader/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/gen-typescript-declarations/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/linter/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/modulizer/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/polyserve/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/project-config/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-browser-legacy/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-sauce/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/web-component-tester/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/workspaces/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/esm-amd-loader/test/node_modules
lerna success clean finished
lerna notice cli v3.2.1
lerna info versioning independent
lerna info Bootstrapping 21 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna WARN EREPLACE_EXIST dom5 is already installed for polymer-build. Replacing with symlink...
lerna info lifecycle wct-local@2.1.1~postinstall: wct-local@2.1.1
lerna info lifecycle wct-sauce@2.1.0~postinstall: wct-sauce@2.1.0

> wct-local@2.1.1 postinstall /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local
> node scripts/postinstall.js

----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar
to: /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/3.12.0-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.40/chromedriver_mac64.zip
to: /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.40-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-macos.tar.gz
to: /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local/node_modules/selenium-standalone/.selenium/geckodriver/0.20.1-x64-geckodriver


-----
selenium-standalone installation finished
-----

> wct-sauce@2.1.0 postinstall /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 7.98MB
Archive checksum verified.
Unzipping /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-sauce/node_modules/sauce-connect-launcher/sc/sc-4.5.1-osx.zip
Removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-sauce/node_modules/sauce-connect-launcher/sc/sc-4.5.1-osx.zip
Sauce Connect downloaded correctly
lerna success Bootstrapped 21 packages
lerna notice cli v3.2.1
lerna info versioning independent
cleankill: npm notice created a lockfile as package-lock.json. You should commit this file.
cleankill: up to date in 0.543s
cleankill: found 0 vulnerabilities
lerna success exec Executed command in 21 packages: "bash -c \"test ! -f package-lock.json && npm install --package-lock-only || true\""
```

### CODE REVIEW

**Comment by usergenic** [comment]
@aomarks I significantly simplified the script on the based on your feedback.

**Comment by usergenic** [comment]
```
λ npm run nuke                                                                 
                             
> polymer-tools@ nuke /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script
> rm -rf package-lock.json node_modules && npm install && lerna exec "rm -f package-lock.json npm-shrinkwrap.json" && lerna clean --yes && lerna bootstrap && lerna exec --stream -- "test -f package-lock.json || npm install --package-lock-only"
                                         
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN sinon-chai@3.2.0 requires a peer of sinon@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
   
added 652 packages from 818 contributors and audited 35789 packages in 14.789s
found 0 vulnerabilities                                                                         
                                                                                                                                                                       
lerna notice cli v3.2.1
lerna info versioning independent
lerna success exec Executed command in 21 packages: "rm -f package-lock.json npm-shrinkwrap.json"
lerna notice cli v3.2.1                                                                                                                                                 
lerna info versioning independent
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/analyzer/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/browser-capabilities/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/build/node_modules                                               
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/bundler/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/cleankill/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/cli/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/common/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/dom5/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/editor-service/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/esm-amd-loader/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/gen-typescript-declarations/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/linter/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/modulizer/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/polyserve/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/project-config/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-browser-legacy/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-sauce/node_modules                           
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/web-component-tester/node_modules               
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/workspaces/node_modules
lerna info clean removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/esm-amd-loader/test/node_modules
lerna success clean finished
lerna notice cli v3.2.1          
lerna info versioning independent                                                          
lerna info Bootstrapping 21 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries                                                                       
lerna WARN EREPLACE_EXIST dom5 is already installed for polymer-build. Replacing with symlink...
lerna info lifecycle wct-local@2.1.1~postinstall: wct-local@2.1.1
lerna info lifecycle wct-sauce@2.1.0~postinstall: wct-sauce@2.1.0

> wct-local@2.1.1 postinstall /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local
> node scripts/postinstall.js                               
                                                                           
----------
selenium-standalone installation starting
----------                      
                                                       
---                                                                
selenium install:                                   
from: https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar
to: /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/3.12.0-server.jar
---                                                  
chrome install:                                    
from: https://chromedriver.storage.googleapis.com/2.40/chromedriver_mac64.zip
to: /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.40-x64-chromedriver
---                                                               
firefox install:                                                          
from: https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-macos.tar.gz
to: /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-local/node_modules/selenium-standalone/.selenium/geckodriver/0.20.1-x64-geckodriver
                                                        
                                                             
-----                                                            
selenium-standalone installation finished               
-----                                                   
                                                                   
> wct-sauce@2.1.0 postinstall /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-sauce
> node scripts/postinstall.js
                                                                 
Prefetching the Sauce Connect binary.                      
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.                                                                        
Downloading 7.98MB                                                            
Archive checksum verified.                    
Unzipping /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-sauce/node_modules/sauce-connect-launcher/sc/sc-4.5.1-osx.zip
Removing /Users/brendanb/src/github.com/Polymer/tools~friendlier-nuke-script/packages/wct-sauce/node_modules/sauce-connect-launcher/sc/sc-4.5.1-osx.zip
Sauce Connect downloaded correctly       
lerna success Bootstrapped 21 packages
lerna notice cli v3.2.1                                     
lerna info versioning independent    
cleankill: npm notice created a lockfile as package-lock.json. You should commit this file.
cleankill: up to date in 0.52s 
cleankill: found 0 vulnerabilities                                     
lerna success exec Executed command in 21 packages: "test -f package-lock.json || npm install --package-lock-only"
```

**Comment by TimvdLippe** [comment]
@usergenic This looks good! I can not run it myself right now, but could you confirm the following script successfully executes after running `npm run nuke`?

```
npx lerna exec --stream -- npm audit
```

**Comment by usergenic** [comment]
```
λ npx lerna exec -- npm audit
lerna notice cli v3.2.1
lerna info versioning independent
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 7 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 0 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 8 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 5445 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 51 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 261 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install mocha@5.2.0  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > debug                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > growl                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/146                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm install lodash@4.17.10  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ stacky                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ stacky > lodash                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 4 vulnerabilities (3 low, 1 critical) in 69 scanned packages
  3 vulnerabilities require semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.
lerna ERR! npm audit exited 1 in 'wct-browser-legacy'
lerna ERR! npm audit exited 1 in 'wct-browser-legacy'
~/s/g/P/tools~friendlier-nuke-script λ 
~/s/g/P/tools~friendlier-nuke-script λ npx lerna exec --stream -- npm audie
^C⏎                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ~/s/g/P/tools~friendlier-nuke-script λ npx lerna exec --stream -- npm audit
lerna notice cli v3.2.1
lerna info versioning independent
browser-capabilities: === npm audit security report ===
browser-capabilities:
browser-capabilities: found 0 vulnerabilities
browser-capabilities:  in 7 scanned packages
cleankill: === npm audit security report ===
cleankill:
cleankill: found 0 vulnerabilities
cleankill:  in 0 scanned packages
dom5: === npm audit security report ===
dom5:
dom5: found 0 vulnerabilities
dom5:  in 8 scanned packages
@polymer/tools-common: === npm audit security report ===
@polymer/tools-common:
@polymer/tools-common: found 0 vulnerabilities
@polymer/tools-common:  in 5445 scanned packages
@polymer/esm-amd-loader: === npm audit security report ===
@polymer/esm-amd-loader:
@polymer/esm-amd-loader: found 0 vulnerabilities
@polymer/esm-amd-loader:  in 261 scanned packages
polymer-workspaces: === npm audit security report ===
polymer-workspaces:
polymer-workspaces: found 0 vulnerabilities
polymer-workspaces:  in 51 scanned packages
wct-browser-legacy: === npm audit security report ===
wct-browser-legacy:
wct-browser-legacy: # Run  npm install mocha@5.2.0  to resolve 2 vulnerabilities
wct-browser-legacy: SEMVER WARNING: Recommended action is a potentially breaking change
wct-browser-legacy: ┌───────────────┬──────────────────────────────────────────────────────────────┐
wct-browser-legacy: │ Low           │ Regular Expression Denial of Service                         │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Package       │ debug                                                        │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Dependency of │ mocha                                                        │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Path          │ mocha > debug                                                │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ More info     │ https://nodesecurity.io/advisories/534                       │
wct-browser-legacy: └───────────────┴──────────────────────────────────────────────────────────────┘
wct-browser-legacy: ┌───────────────┬──────────────────────────────────────────────────────────────┐
wct-browser-legacy: │ Critical      │ Command Injection                                            │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Package       │ growl                                                        │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Dependency of │ mocha                                                        │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Path          │ mocha > growl                                                │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ More info     │ https://nodesecurity.io/advisories/146                       │
wct-browser-legacy: └───────────────┴──────────────────────────────────────────────────────────────┘
wct-browser-legacy: # Run  npm install lodash@4.17.10  to resolve 1 vulnerability
wct-browser-legacy: SEMVER WARNING: Recommended action is a potentially breaking change
wct-browser-legacy: ┌───────────────┬──────────────────────────────────────────────────────────────┐
wct-browser-legacy: │ Low           │ Prototype Pollution                                          │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Package       │ lodash                                                       │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Dependency of │ lodash                                                       │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Path          │ lodash                                                       │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ More info     │ https://nodesecurity.io/advisories/577                       │
wct-browser-legacy: └───────────────┴──────────────────────────────────────────────────────────────┘
wct-browser-legacy: ┌──────────────────────────────────────────────────────────────────────────────┐
wct-browser-legacy: │                                Manual Review                                 │
wct-browser-legacy: │            Some vulnerabilities require your attention to resolve            │
wct-browser-legacy: │                                                                              │
wct-browser-legacy: │         Visit https://go.npm.me/audit-guide for additional guidance          │
wct-browser-legacy: └──────────────────────────────────────────────────────────────────────────────┘
wct-browser-legacy: ┌───────────────┬──────────────────────────────────────────────────────────────┐
wct-browser-legacy: │ Low           │ Prototype Pollution                                          │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Package       │ lodash                                                       │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Patched in    │ >=4.17.5                                                     │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Dependency of │ stacky                                                       │
wct-browser-legacy: ├──��────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ Path          │ stacky > lodash                                              │
wct-browser-legacy: ├───────────────┼──────────────────────────────────────────────────────────────┤
wct-browser-legacy: │ More info     │ https://nodesecurity.io/advisories/577                       │
wct-browser-legacy: └───────────────┴──────────────────────────────────────────────────────────────┘
wct-browser-legacy: found 4 vulnerabilities (3 low, 1 critical) in 69 scanned packages
wct-browser-legacy:   3 vulnerabilities require semver-major dependency updates.
wct-browser-legacy:   1 vulnerability requires manual review. See the full report for details.
lerna ERR! npm audit exited 1 in 'wct-browser-legacy'
lerna ERR! npm audit stdout:
=== npm audit security report ===
```

So now the only fail is wct-browser-legacy because it legitimately fails audit.

**Comment by TimvdLippe** [comment]
Awesome work, thanks Brendan!!

**Pull request merged**
