### PR TITLE
[wct] Use gts for linting and formatting

### LINKED ISSUE #224: [wct] Moving from clang + tslint to gts
Google has a nice tool which combines capabilities of tslint and clang fromat in one tool: https://github.com/google/ts-style

The issue with the current configuration is that clang and tslint rules are conflicting. Originally I wanted to tweak tslint configuration, but in the end I think moving to gts is a better idea.

Is that ok with you guys if I make a PR for this?

### PR DESCRIPTION
**Pull request by koshilki**
- Use `gts` instead of `tslint`+`clang-format`
- Lint using NPM scripts instead of `gulp`
- Fix formatting according to gts rules
- Fix `gts` lint rules violations
- Refactor clireporter status colorise method

Fixes #224 

Co-authored-by: @merlinnot

### CODE REVIEW

**Comment by koshilki** [comment]
@merlinnot FYI

**Comment by merlinnot** [comment]
I'm ok with my work being contributed to Google.

**Comment by koshilki** [comment]
@googlebot CLA issue should be fixed by now

**Review by merlinnot — APPROVED** [review]
LGTM once we merge koshilki/tools#1

**Pull request closed without merging**
