### PR TITLE
cli: update chalk dependency

### PR DESCRIPTION
**Pull request by 43081j**
I was in there for #612 so figured i'd split out the chalk update i did as part of my debugging.

We don't really need this but it does mean we're depending on the same version as `command-line-usage` so there's no more mismatch funkiness going on.

### CODE REVIEW

**Comment by srawlins** [comment]
This PR needs to be rebased.

**Comment by 43081j** [comment]
Yup, a few of my PRs have aged a little in this repo so ill try get around to rebasing them all if someone now has time to review/merge.

**Comment by 43081j** [comment]
yup i left WCT related stuff because of the ongoing work around it.

i've rebased anyhow

**Comment by usergenic** [comment]
Closing in favor of https://github.com/Polymer/tools/pull/3444 which just allowed me to get around resolving package-lock.json conflicts through the github UI.

**Pull request closed without merging**
