### PR TITLE
[polyserve] bump mime to 2.x

### LINKED ISSUE #415: [polyserve] Update `mime` dependency
*.mjs files currently have the wrong MIME type (with "mime": "^1.3.4").
Can we update the mime dependency to a version that correctly marks *.mjs files with the correct MIME type ("application/javascript") [^2.0.4]?

### PR DESCRIPTION
**Pull request by 43081j**
Fixes #415.

Just bumped mime to its 2.x branch and fixed the single reference we have of it. Seems their 1 -> 2 breaking change was just API renaming.

WCT seemed to have the types too, but didn't have `mime` its self as a dep.. so i removed it. let me know if that was somehow a mistake.

If #395 gets merged first i will rebase and have npm sort the lock conflicts.

cc @justinfagnani

### CODE REVIEW

**Comment by web-padawan** [comment]
@43081j I was wondering if this is also expected to be handful for `polymer analyze`?
As of now, the `.js` bundle can be analysed but the exact same file with `.mjs` extension produced empty output.

/cc @rictic

**Comment by 43081j** [comment]
@TimvdLippe i've rebased it to master.

the WCT package lock diff is pretty much unreviewable, shall we just assume it is fine? removing mime changed the lock a lot...

as for the audits, i can `npm audit fix` but that will add more version bumps we don't have in master.

**Comment by 43081j** [comment]
we also get this now...

```
> web-component-tester@6.7.1 build /home/travis/build/Polymer/tools/packages/web-component-tester
> tsc && gulp build
runner/webserver.ts:222:9 - error TS2345: Argument of type '(app: Express, options: ServerOptions) => Promise<Express>' is not assignable to parameter of type 'ExpressAppMapper'.
  Type 'Promise<e.Express>' is not assignable to type 'Promise<e.Express>'. Two different types with this name exist, but they are unrelated.
    Type 'e.Express' is not assignable to type 'e.Express'. Two different types with this name exist, but they are unrelated.
      Property 'mountpath' is missing in type 'Express'.
222         appMapper);
            ~~~~~~~~~
runner/webserver.ts:249:13 - error TS2322: Type 'any' is not assignable to type 'never'.
249       const never: never = polyserveResult;
                ~~~~~
```

**Comment by TimvdLippe** [comment]
Oh sorry, I meant the audit in polyserve. Wct I am working on in a different PR. Will take a look tomorrow.

**Comment by 43081j** [comment]
ah polyserve reports 1 low vulnerability (deep-extend). same as master?

**Comment by 43081j** [comment]
@TimvdLippe i dropped the changes to wct now

**Pull request merged**
