### PR TITLE
Fix WCT for bower: use Polymer version of sinon.js

### LINKED ISSUE #3488: web-component-tester fails to install: sinonjs repository not found
The `https://github.com/blittle/sinon.js` repository appears to have been deleted and WCT is now not able to be installed.

```bash
$ bower install web-component-tester
npx: installed 1 in 3.301s
bower web-component-tester#*    cached https://github.com/Polymer/web-component-tester.git#6.5.0
bower web-component-tester#*  validate 6.5.0 against https://github.com/Polymer/web-component-tester.git#*
bower async#^1.5.0              cached https://github.com/caolan/async.git#1.5.2
bower async#^1.5.0            validate 1.5.2 against https://github.com/caolan/async.git#^1.5.0
bower accessibility-developer-tools#^2.10.0           cached https://github.com/GoogleChrome/accessibility-developer-tools.git#2.12.0
bower accessibility-developer-tools#^2.10.0         validate 2.12.0 against https://github.com/GoogleChrome/accessibility-developer-tools.git#^2.10.0
bower sinon-chai#^2.7.0                               cached https://github.com/domenic/sinon-chai.git#2.14.0
bower sinon-chai#^2.7.0                             validate 2.14.0 against https://github.com/domenic/sinon-chai.git#^2.7.0
bower chai#^3.2.0                                     cached https://github.com/chaijs/chai.git#3.5.0
bower chai#^3.2.0                                   validate 3.5.0 against https://github.com/chaijs/chai.git#^3.2.0
bower lodash#^3.7.0                                   cached https://github.com/lodash/lodash.git#3.10.1
bower lodash#^3.7.0                                 validate 3.10.1 against https://github.com/lodash/lodash.git#^3.7.0
bower stacky#^1.3.0                                   cached https://github.com/PolymerLabs/stacky.git#1.3.2
bower stacky#^1.3.0                                 validate 1.3.2 against https://github.com/PolymerLabs/stacky.git#^1.3.0
bower mocha#^3.1.2                                    cached https://github.com/mochajs/mocha.git#3.5.3
bower mocha#^3.1.2                                  validate 3.5.3 against https://github.com/mochajs/mocha.git#^3.1.2
bower sinonjs#^1.14.1                                 cached https://github.com/blittle/sinon.js.git#1.17.1
bower sinonjs#^1.14.1                               validate 1.17.1 against https://github.com/blittle/sinon.js.git#^1.14.1
bower test-fixture#^3.0.0                             cached https://github.com/PolymerElements/test-fixture.git#3.0.0
bower test-fixture#^3.0.0                           validate 3.0.0 against https://github.com/PolymerElements/test-fixture.git#^3.0.0
Username for 'https://github.com':        
Password for 'https://github.com': 
bower sinonjs#^1.14.1                                ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/blittle/sinon.js.git", exit code of #128 remote: Repository not found. fatal: Authentication failed for 'https://github.com/blittle/sinon.js.git/'

Additional error details:
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/blittle/sinon.js.git/'
```

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #3488

This is a fix for the critical issue that affects our bower installations:

```
bower sinonjs#^1.14.1                                ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/blittle/sinon.js.git", exit code of #128 remote: Invalid username or password. fatal: Authentication failed for 'https://github.com/blittle/sinon.js.git/'
Additional error details:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/blittle/sinon.js.git/'
```

Ping @justinfagnani @usergenic.

### CODE REVIEW

**Comment by justinfagnani** [comment]
The integration tests are timing out on Chrome 80. This has been happening elsewhere though, see https://github.com/Polymer/lit-html/issues/1080 and https://github.com/Polymer/lit-html/pull/1078

**Comment by web-padawan** [comment]
@justinfagnani thanks. BTW, am I right that in order to make a release for Bower, this PR should go into (now archived) original [web-component-tester](https://github.com/Polymer/web-component-tester) repository?

At least `bower search` still points to that location:

```sh
$ bower search web-component-tester
Search results:

    web-component-tester https://github.com/Polymer/web-component-tester.git
```

**Comment by justinfagnani** [comment]
@web-padawan I think you're right. cc @dfreedm @usergenic

**Comment by justinfagnani** [comment]
We've unarchived the old repo and will add this fix there and tag a new release for Bower.

**Comment by web-padawan** [comment]
Thanks a lot 🙇 Feel free to close this PR in that case.

**Pull request closed without merging**
