### PR TITLE
Fix: WCT CLI arg standardizing

### LINKED ISSUE #416: polymer test `--config-file` is ignored
`polymer test --help` says:
~~~
  --config-file string             Config file that needs to be used by wct. ie: wct.config-sauce.js             
~~~~

Looking through https://github.com/Polymer/tools/blob/219ab4f3f9f8773e75f8c6181109e8966082b9af/packages/cli/src/commands/test.ts#L139-L157: The argument is passed directly to wct's cli.

That one however expects `configFile`: https://github.com/Polymer/tools/blob/219ab4f3f9f8773e75f8c6181109e8966082b9af/packages/web-component-tester/runner/config.ts#L349-L352

I'm not sure how to resolve this, as `polymer-cli` has both options with camelCase and with dash-case.

Right now though the result of this is that `--config-file` doesn't work, and I need to do something like this in Travis: `mv travis-wct.conf.json wct.conf.json`. Clearly ugly :/

### PR DESCRIPTION
**Pull request by stramel**
Supersedes https://github.com/Polymer/web-component-tester/pull/698

Fixes #416 https://github.com/Polymer/polymer-cli/issues/919 https://github.com/Polymer/web-component-tester/issues/652 

@usergenic

### CODE REVIEW

**Comment by stramel** [comment]
Or is it a fix since it should have been this way in the first place? 🤔 😛

**Comment by merlinnot** [comment]
😂

**Comment by usergenic** [comment]
hmm https://github.com/search?q=polymer+test+--configFile&type=Code

**Comment by stramel** [comment]
@usergenic I wonder if I could set `alias: 'configFile'`?

**Comment by usergenic** [comment]
@stramel that occurred to me too. haven't tested it but thats probably the way to go.

**Comment by stramel** [comment]
Yeah, I won't be able to test until I get home. But if it works I will update the PR and add a note

**Comment by merlinnot** [comment]
Maybe a deprecation warning on top of this? So we can actually drop it some day?

**Comment by stramel** [comment]
:/ alias can only be a single character... I will look into a different way to resolve that issue.

**Comment by stramel** [comment]
@usergenic Perhaps this is just a happy coincidence but this isn't a breaking change oddly enough. It is "breaking" in the sense that we are deprecating the `configFile` and `simpleOutput` option. However, `nomnom` the arg parser that is used in `web-component-tester` will match `configFile` and `config-file` after these changes. Where as previously it did not match `config-file` as `configFile`.

Technically speaking any arg listed camelCase in the definition list will work camelCase even with `full` specified as dash-case. 

**NOTE:** `nomnom` is deprecated and would probably be useful to move to `command-line-args` like the other packages on the next major breaking change release and coordinate that with the remove of camelCase arg support.

**Comment by usergenic** [comment]
@stramel whoa!  how about that!  okay, that's great work looking into that.  After we merge this I'll add a test or something to ensure handling of both forms in the event someone decides to upgrade wct's arg parsing without knowing all this.

**Comment by usergenic** [comment]
I'll get this merged before tomorrow as soon as I can set aside a moment to craft that test.

**Comment by usergenic** [comment]
Had some other issues with CLI release branch on Friday; Will get this merged *today* (if possible!)

**Comment by stramel** [comment]
No worries! Thanks again @usergenic!

**Comment by usergenic** [comment]
@stramel this is getting released shortly after https://github.com/Polymer/tools/pull/515 gets approved. :)

**Pull request merged**
