### PR TITLE
upgrade to sinon 5.x

### LINKED ISSUE #228: [wct] Update Sinon to the latest version
Analogous to https://github.com/Polymer/tools/issues/227

### PR DESCRIPTION
**Pull request by 43081j**
just bumping sinon to 5.x.

Fixes #228.

the types aren't quite right but they work for us it seems (they get fixed in DefinitelyTyped/DefinitelyTyped#25491).

is this fine? wct was an odd one, it still has `@polymer/sinonjs`.. do we need that still?

cc @rictic

### CODE REVIEW

**Comment by merlinnot** [comment]
So you work on types for Sinon and you contribute to Polymer/tools? Much love mate ❤️

**Comment by 43081j** [comment]
FYI the sinon 5.x types have been merged now.

ill try rebase this at the weekend and pull in the new types. though because lock files are such a pain to fix conflicts in, i may just start again 🙈

**Comment by merlinnot** [comment]
You can always regenerate lockfiles :)

**Comment by 43081j** [comment]
turns out npm automatically resolves git conflicts in package-lock.json files as long as your package.json is resolved!

tests pass but the diff on the lock files looks unusually different considering the small footprint of my change. if i regen them all the additions seem to stick around so i guess its right?

cc @rictic  maybe? to get this merged/checked

**Comment by merlinnot** [comment]
@43081j AppVeyor

**Comment by 43081j** [comment]
doesn't look like the result on my changes:

```
info: [cli.install]    Installing npm dependencies...
error: [cli.main]   cli runtime exception: Error: Command failed: npm install
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
npm ERR! 
```

something specific to appveyor or how we have it configured maybe?

**Comment by justinfagnani** [comment]
@43081j is this a breaking change?

**Comment by justinfagnani** [comment]
I'm wondering if for test code that uses sinon as provided will break, which would require a major-version bump of wct-browser-legacy

**Comment by merlinnot** [comment]
It has it's own package.json: https://github.com/Polymer/tools/blob/master/packages/web-component-tester/wct-browser-legacy/package.json

**Comment by 43081j** [comment]
@justinfagnani any chance we can get this merged? if i need to change something to avoid needing a breaking change, let me know.

just want to avoid the pr going stale

**Comment by 43081j** [comment]
@TimvdLippe i reverted the wct changes 

i didn't change my original commit so i can keep the code changes locally

**Comment by ernsheong** [comment]
@TimvdLippe 

Any update regarding `web-component-tester`?

**Comment by TimvdLippe** [comment]
That update is being done separately atm. See the work on wct-mocha et al in other PRs.

**Comment by osamamaruf** [comment]
Till the sinon version is bumped should't  #228 be kept open? (its 7.x now)

**Pull request merged**
